[project]
name = "hello-bazel-pycon-il"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
